#pragma once

#include "KObject.h"
#include <array>
#include "vecmat.h"
#include "CKPartlyUnknown.h"
#include "CKUtils.h"
#include "Events.h"

struct CKHookLife;
struct CKGrpBonusPool;
struct CKGrpWildBoarPool;
struct CAnimationDictionary;
struct CKSceneNode;
struct CKBoundingShape;
struct CAnimatedClone;
struct CKHook;
struct CKSoundDictionaryID;
struct CKFlaggedPath;
struct CAnimatedNode;
struct CDynamicGround;
struct CSGBranch;
struct CNode;
struct CClone;
struct CKHkWaterFx;
struct CKProjectileTypeScrap;
struct CParticlesNodeFx;
struct CKBoundingSphere;
struct CKOBB;
struct CKSpline4L;
struct CKAABB;
struct CKShadowCpnt;
struct CKProjectileTypeBase;
struct CGround;
struct CKProjectileTypeBallisticPFX;
struct CKCrateCpnt;
struct CColorTextButton2d;
struct CText2d;
struct CBillboard2d;
struct CKGrpCatapult;

using MarkerIndex = int32_t;

struct CKHook : CKMRSubclass<CKHook, CKMemberReflectable<CKCategory<2>>, 0> {
	kobjref<CKHook> next;
	uint32_t unk1 = 0;
	kobjref<CKHookLife> life;
	KPostponedRef<CKSceneNode> node;

	// XXL2+:
	uint32_t x2UnkA, x2UnkB;

	void reflectMembers(MemberListener &r);
	void deserialize(KEnvironment* kenv, File *file, size_t length) override;
	void serialize(KEnvironment* kenv, File *file) override;
	void onLevelLoaded(KEnvironment *kenv) override;
};

struct CKHookLife : CKCategory<3> {
	kobjref<CKHook> hook;
	kobjref<CKHookLife> nextLife;
	uint32_t unk1 = 0;

	void deserialize(KEnvironment* kenv, File *file, size_t length) override;
	void serialize(KEnvironment* kenv, File *file) override;
};

struct CKHkPressionStone : CKMRSubclass<CKHkPressionStone, CKHook, 21> {
	kobjref<CKObject> psSquad;
	KPostponedRef<CKObject> psDynGround;
	kobjref<CKObject> psSndDict;
	EventNode psEvtSeq1;
	EventNode psEvtSeq2;
	float psUnk5;
	float psUnk6;
	float psUnk7;
	float psUnk8;
	void reflectMembers(MemberListener &r);
};
struct CKHkHero : CKMRSubclass<CKHkHero, CKHook, 25> {
	kobjref<CKObject> heroGrpTrio;
	uint8_t heroUnk1;
	uint8_t heroUnk2;
	float heroUnk3;
	float heroUnk4;
	float heroUnk5;
	float heroUnk6;
	float heroUnk7;
	float heroUnk8;
	float heroUnk9;
	float heroUnk10;
	float heroUnk11;
	kobjref<CKObject> heroBranch1;
	float heroUnk13;
	float heroUnk14;
	float heroUnk15;
	float heroUnk16;
	float heroUnk17;
	float heroUnk18;
	float heroUnk19;
	float heroUnk20;
	float heroUnk21;
	float heroUnk22;
	float heroUnk23;
	kobjref<CKObject> heroAnimDict;
	float heroUnk25;
	Vector3 heroUnk26;
	Vector3 heroUnk27;
	float heroUnk28;
	float heroUnk29;
	kobjref<CKObject> heroBranch2;
	Vector3 heroUnk31;
	uint8_t heroUnk32;
	float heroUnk33;
	float heroUnk34;
	float heroUnk35;
	std::array<float, 4> heroUnk36;
	std::array<float, 4> heroUnk37;
	std::array<uint8_t, 3> heroUnk38;
	float heroUnk39;
	kobjref<CKObject> heroSphere;
	float heroUnk41;
	float heroUnk42;
	kobjref<CKObject> heroDynSphere;
	kobjref<CKObject> heroCylinder;
	float heroUnk45;
	float heroUnk46;
	kobjref<CKObject> heroParticleNode;
	kobjref<CKObject> heroTrailNode;
	kobjref<CKObject> heroSndDict;
	float heroUnk50;
	float heroUnk51;
	float heroUnk52;
	std::vector<Vector3> heroUnk53;
	std::vector<Vector3> heroUnk54;
	std::vector<uint8_t> heroUnk55;
	std::vector<uint8_t> heroUnk56;
	std::vector<uint8_t> heroUnk57;
	float heroUnk58;
	float heroUnk59;
	float heroUnk60;
	float heroUnk61;
	float heroUnk62;
	float heroUnk63;
	float heroUnk64;
	float heroUnk65;
	float heroUnk66;
	float heroUnk67;
	float heroUnk68;
	float heroUnk69;
	float heroUnk70;
	float heroUnk71;
	float heroUnk72;
	float heroUnk73;
	float heroUnk74;
	float heroUnk75;
	float heroUnk76;
	float heroUnk77;
	float heroUnk78;
	float heroUnk79;
	float heroUnk80;
	float heroUnk81;
	float heroUnk82;
	float heroUnk83;
	kobjref<CKObject> heroBranch3;
	float heroUnk85;
	float heroUnk86;
	float heroUnk87;
	float heroUnk88;
	float heroUnk89;
	float heroUnk90;
	float heroUnk91;
	float heroUnk92;
	float heroUnk93;
	uint8_t heroUnk94;
	float heroUnk95;
	float heroUnk96;
	float heroUnk97;
	float heroUnk98;
	float heroUnk99;
	float heroUnk100;
	float heroUnk101;
	float heroUnk102;
	float heroUnk103;
	float heroUnk104;
	float heroUnk105;
	float heroUnk106;
	float heroUnk107;
	std::array<float, 8> heroUnk108;
	float heroUnk109;
	float heroUnk110;
	float heroUnk111;
	float heroUnk112;
	float heroUnk113;
	uint8_t heroUnk114;
	uint8_t heroUnk115;
	float heroUnk116;
	float heroUnk117;
	float heroUnk118;
	float heroUnk119;
	float heroUnk120;
	uint8_t heroUnk121;
	float heroUnk122;
	float heroUnk123;
	float heroUnk124;
	float heroUnk125;
	float heroUnk126;
	float heroUnk127;
	float heroUnk128;
	float heroUnk129;
	uint8_t heroUnk130;
	std::array<float, 16> heroUnk131;
	std::array<float, 2> heroUnk132;
	float heroUnk133;
	float heroUnk134;
	float heroUnk135;
	float heroUnk136;
	float heroUnk137;
	float heroUnk138;
	float heroUnk139;
	float heroUnk140;
	float heroUnk141;
	std::array<float, 5> heroUnk142;
	float heroUnk143;
	float heroUnk144;
	float heroUnk145;
	std::array<float, 16> heroUnk146;
	float heroUnk147;
	float heroUnk148;
	float heroUnk149;
	float heroUnk150;
	float heroUnk151;
	float heroUnk152;
	float heroUnk153;
	float heroUnk154;
	float heroUnk155;
	float heroUnk156;
	float heroUnk157;
	float heroUnk158;
	float heroUnk159;
	float heroUnk160;
	float heroUnk161;
	float heroUnk162;
	float heroUnk163;
	float heroUnk164;
	float heroUnk165;
	float heroUnk166;
	float heroUnk167;
	float heroUnk168;
	float heroUnk169;
	float heroUnk170;
	float heroUnk171;
	float heroUnk172;
	float heroUnk173;
	float heroUnk174;
	float heroUnk175;
	kobjref<CKObject> heroShadowCpnt;
	kobjref<CKObject> heroWaterFxHook;
	float heroUnk178;
	void reflectMembers2(MemberListener &r, KEnvironment *kenv);
};
struct CKHkAsterix : CKMRSubclass<CKHkAsterix, CKHkHero, 28> {
	int32_t asteUnk0;
	float asteUnk1;
	float asteUnk2;
	float asteUnk3;
	float asteUnk4;
	float asteUnk5;
	float asteUnk6;
	float asteUnk7;
	float asteUnk8;
	float asteUnk9;
	float asteUnk10;
	float asteUnk11;
	float asteUnk12;
	float asteUnk13;
	float asteUnk14;
	float asteUnk15;
	float asteUnk16;
	float asteUnk17;
	float asteUnk18;
	float asteUnk19;
	float asteUnk20;
	float asteUnk21;
	float asteUnk22;
	float asteUnk23;
	float asteUnk24;
	kobjref<CKObject> asteDynSphere1;
	kobjref<CKObject> asteDynSphere2;
	kobjref<CKObject> asteBranch1;
	kobjref<CKObject> asteBranch2;
	float asteUnk29;
	float asteUnk30;
	kobjref<CKObject> asteSphere1;
	kobjref<CKObject> asteSphere2;
	kobjref<CKObject> asteBranch3;
	kobjref<CKObject> asteBranch4;
	kobjref<CKObject> asteParticleNode0;
	kobjref<CKObject> asteParticleNode1;
	kobjref<CKObject> asteParticleNode2;
	kobjref<CKObject> asteParticleNode3;
	kobjref<CKObject> asteParticleNode4;
	kobjref<CKObject> asteParticleNode5;
	kobjref<CKObject> asteParticleNode6;
	kobjref<CKObject> asteParticleNode7;
	kobjref<CKObject> asteParticleNode8;
	kobjref<CKObject> asteParticleNode9;
	kobjref<CKObject> asteParticleNode10;
	kobjref<CKObject> asteParticleNode11;
	kobjref<CKObject> asteParticleNode12;
	kobjref<CKObject> asteParticleNode13;
	kobjref<CKObject> asteParticleNode14;
	kobjref<CKObject> asteParticleNode15;
	kobjref<CKObject> asteParticleNode16;
	kobjref<CKObject> asteBranch5;
	kobjref<CKObject> asteBranch6;
	void reflectMembers2(MemberListener &r, KEnvironment *kenv);
};
struct CKHkObelix : CKMRSubclass<CKHkObelix, CKHkHero, 29> {
	float obeUnk0;
	kobjref<CKObject> obeDynSphere1;
	kobjref<CKObject> obeDynSphere2;
	kobjref<CKObject> obeBranchA1;
	kobjref<CKObject> obeBranchA2;
	float obeUnk5;
	float obeUnk6;
	float obeUnk7;
	kobjref<CKObject> obeSphere1;
	kobjref<CKObject> obeSphere2;
	kobjref<CKObject> obeBranchB1;
	kobjref<CKObject> obeBranchB2;
	kobjref<CKObject> obeParticleNode0;
	kobjref<CKObject> obeParticleNode1;
	kobjref<CKObject> obeParticleNode2;
	kobjref<CKObject> obeParticleNode3;
	kobjref<CKObject> obeParticleNode4;
	kobjref<CKObject> obeParticleNode5;
	kobjref<CKObject> obeParticleNode6;
	kobjref<CKObject> obeParticleNode7;
	kobjref<CKObject> obeParticleNode8;
	kobjref<CKObject> obeParticleNode9;
	kobjref<CKObject> obeParticleNode10;
	kobjref<CKObject> obeParticleNode11;
	kobjref<CKObject> obeParticleNode12;
	kobjref<CKObject> obeParticleNode13;
	kobjref<CKObject> obeParticleNode14;
	kobjref<CKObject> obeParticleNode15;
	kobjref<CKObject> obeParticleNode16;
	kobjref<CKObject> obeParticleNode17;
	kobjref<CKObject> obeBranchE1;
	kobjref<CKObject> obeBranchE2;
	kobjref<CKObject> obeBranchE3;
	kobjref<CKObject> obeBranchE4;
	kobjref<CKObject> obeBranchE5;
	kobjref<CKObject> obeBranchE6;
	void reflectMembers2(MemberListener &r, KEnvironment *kenv);
};
struct CKHkIdefix : CKMRSubclass<CKHkIdefix, CKHkHero, 30> {
	float ideUnk0;
	kobjref<CKObject> ideSphere;
	kobjref<CKObject> ideBranch;
	float ideUnk3;
	float ideUnk4;
	float ideUnk5;
	float ideUnk6;
	uint8_t ideUnk7;
	kobjref<CKObject> ideParticleNode1;
	kobjref<CKObject> ideParticleNode2;
	void reflectMembers2(MemberListener &r, KEnvironment *kenv);
};

struct CKHkMachinegun : CKMRSubclass<CKHkMachinegun, CKHook, 31> {
	float mgunUnk0;
	float mgunUnk1;
	kobjref<CKObject> mgunSpline;
	float mgunUnk3;
	float mgunUnk4;
	Vector3 mgunUnk5;
	float mgunUnk6;
	float mgunUnk7;
	float mgunUnk8;
	float mgunUnk9;
	float mgunUnk10;
	float mgunUnk11;
	float mgunUnk12;
	uint8_t mgunUnk13;
	uint8_t mgunUnk14;
	float mgunUnk15;
	float mgunUnk16;
	float mgunUnk17;
	float mgunUnk18;
	float mgunUnk19;
	float mgunUnk20;
	float mgunUnk21;
	kobjref<CKObject> mgunAnimDict;
	kobjref<CKObject> mgunSndDict;
	kobjref<CKObject> mgunAnimNode;
	kobjref<CKObject> mgunNode;
	Vector3 mgunUnk26;
	kobjref<CKObject> mgunParticles1;
	kobjref<CKObject> mgunParticles2;
	kobjref<CKObject> mgunParticles3;
	float mgunUnk30;
	float mgunUnk31;
	float mgunUnk32;
	float mgunUnk33;
	std::array<kobjref<CKObject>, 4> mgunClones;
	Vector3 mgunUnk35;
	float mgunUnk36;
	float mgunUnk37;
	float mgunUnk38;
	float mgunUnk39;
	float mgunUnk40;
	kobjref<CKObject> mgunBranch1;
	kobjref<CKObject> mgunBranch2;
	kobjref<CKObject> mgunBranch3;
	kobjref<CKObject> mgunBranch4;
	uint8_t mgunUnk45;
	EventNode mgunUnk46;
	EventNode mgunUnk47;
	KPostponedRef<CKObject> mgunDynGround1;
	KPostponedRef<CKObject> mgunDynGround2;
	kobjref<CKObject> mgunProjectile;
	Vector3 mgunUnk51;
	Vector3 mgunUnk52;
	kobjref<CKObject> mgunShadowCpnt;
	float mgunUnk54;
	uint8_t mgunUnk55;
	void reflectMembers2(MemberListener &r, KEnvironment* kenv);
};


struct CKHkTorch : CKMRSubclass<CKHkTorch, CKHook, 32> {
	kobjref<CKObject> torchSndDict;
	kobjref<CKObject> torchBranch;
	float torchUnk2;
	float torchUnk3;
	float torchUnk4;
	float torchUnk5;
	float torchUnk6;
	uint8_t torchUnk7;
	Matrix torchUnk8;
	EventNode torchEvtSeq1;
	EventNode torchEvtSeq2;
	EventNode torchEvtSeq3;
	void reflectMembers(MemberListener &r);
};
struct CKHkHearth : CKMRSubclass<CKHkHearth, CKHook, 33> {
	kobjref<CKObject> hearthSndDict;
	KPostponedRef<CKObject> hearthDynGround;
	EventNode hearthEvtSeq1;
	EventNode hearthEvtSeq2;
	EventNode hearthEvtSeq3;
	EventNode hearthEvtSeq4;
	EventNode hearthEvtSeq5;
	float hearthUnk7;
	float hearthUnk8;
	Vector3 hearthUnk9, hearthUnk10;
	void reflectMembers(MemberListener &r);
};
struct CKHkDrawbridge : CKMRSubclass<CKHkDrawbridge, CKHook, 34> {
	KPostponedRef<CKObject> dbStaticGround;
	KPostponedRef<CKObject> dbDynGround;
	kobjref<CKObject> dbSndDict;
	EventNode dbEvtSeq;
	float dbUnk4;
	float dbUnk5;
	float dbUnk6;
	float dbUnk7;
	float dbUnk8;
	void reflectMembers(MemberListener &r);
};
struct CKHkMegaAshtray : CKMRSubclass<CKHkMegaAshtray, CKHook, 37> {
	kobjref<CKObject> maAnimDict;
	kobjref<CKObject> maSndDict;
	KPostponedRef<CKObject> maDynGround1;
	KPostponedRef<CKObject> maDynGround2;
	float maUnk4;
	float maUnk5;
	void reflectMembers(MemberListener &r);
};
struct CKHkBoat : CKMRSubclass<CKHkBoat, CKHook, 39> {
	float ckhbUnk3;
	float ckhbUnk4;
	float ckhbUnk5;
	float ckhbUnk6;
	float ckhbUnk7;
	uint8_t ckhbUnk8;
	float ckhbUnk9;
	float ckhbUnk10;
	float ckhbUnk11;
	float ckhbUnk12;
	float ckhbUnk13;
	float ckhbUnk14;
	float ckhbUnk15;
	float ckhbUnk16;
	float ckhbUnk17;
	float ckhbUnk18;
	float ckhbUnk19;
	float ckhbUnk20;
	float ckhbUnk21;
	float ckhbUnk22;
	float ckhbUnk23;
	float ckhbUnk24;
	float ckhbUnk25;
	float ckhbUnk26;
	float ckhbUnk27;
	float ckhbUnk28;
	float ckhbUnk29;
	float ckhbUnk30;
	float ckhbUnk31;
	float ckhbUnk32;
	float ckhbUnk33;
	float ckhbUnk34;
	float ckhbUnk35;
	float ckhbUnk36;
	float ckhbUnk37;
	float ckhbUnk38;
	float ckhbUnk39;
	float ckhbUnk40;
	float ckhbUnk41;
	float ckhbUnk42;
	float ckhbUnk43;
	kobjref<CNode> ckhbUnk44;
	kobjref<CAnimatedNode> ckhbUnk45;
	KPostponedRef<CDynamicGround> ckhbUnk46;
	kobjref<CSGBranch> ckhbUnk47;
	kobjref<CSGBranch> ckhbUnk48;
	kobjref<CSGBranch> ckhbUnk49;
	kobjref<CKFlaggedPath> ckhbUnk50;
	float ckhbUnk51;
	int32_t ckhbUnk52;
	uint8_t ckhbUnk53;
	std::array<kobjref<CClone>, 64> ckhbUnk54;
	kobjref<CAnimationDictionary> ckhbUnk55;
	kobjref<CAnimationDictionary> ckhbUnk56;
	float ckhbUnk57;
	float ckhbUnk58;
	uint8_t ckhbUnk59;
	float ckhbUnk60;
	float ckhbUnk61;
	kobjref<CAnimatedNode> ckhbUnk62;
	uint8_t ckhbUnk63;
	float ckhbUnk64;
	float ckhbUnk65;
	kobjref<CKHkWaterFx> ckhbUnk66;
	int32_t ckhbUnk67;
	std::array<float, 4> ckhbUnk68;
	EventNode ckhbUnk69;
	EventNode ckhbUnk70;
	kobjref<CKProjectileTypeScrap> ckhbUnk71;
	kobjref<CParticlesNodeFx> ckhbUnk72;
	MarkerIndex ckhbUnk73;
	MarkerIndex ckhbUnk74;
	kobjref<CParticlesNodeFx> ckhbUnk75;
	kobjref<CParticlesNodeFx> ckhbUnk76;
	kobjref<CParticlesNodeFx> ckhbUnk77;
	kobjref<CParticlesNodeFx> ckhbUnk78;
	float ckhbUnk79;
	float ckhbUnk80;
	kobjref<CKSoundDictionaryID> ckhbUnk81;
	float ckhbUnk82;
	float ckhbUnk83;
	void reflectMembers2(MemberListener& r, KEnvironment* kenv);
};
struct CKHkCorkscrew : CKMRSubclass<CKHkCorkscrew, CKHook, 44> {
	KPostponedRef<CKObject> cswDynGround;
	kobjref<CKObject> cswSndDict;
	MarkerIndex cswUnk2;
	EventNode cswUnk3;
	EventNode cswUnk4;
	float cswUnk5;
	float cswUnk6;
	float cswUnk7;
	float cswUnk8;
	float cswUnk9;
	float cswUnk10;
	float cswUnk11;
	void reflectMembers(MemberListener &r);
};
struct CKHkTurnstile : CKMRSubclass<CKHkTurnstile, CKHook, 45> {
	KPostponedRef<CKObject> tsDynGround;
	kobjref<CKObject> tsSndDict;
	kobjref<CKObject> tsCylinder;
	EventNode tsUnk3;
	EventNode tsUnk4;
	EventNode tsUnk5;
	float tsUnk6;
	float tsUnk7;
	float tsUnk8;
	void reflectMembers(MemberListener &r);
};
struct CKHkLifter : CKMRSubclass<CKHkLifter, CKHook, 47> {
	kobjref<CKObject> liftSquad;
	KPostponedRef<CKObject> liftDynGround;
	KPostponedRef<CKObject> liftStaticGround;
	KPostponedRef<CKObject> liftNode1;
	KPostponedRef<CKObject> liftNode2;
	kobjref<CKObject> liftSndDict;
	float liftUnk6;
	float liftUnk7;
	float liftUnk8;
	float liftUnk9;
	float liftUnk10;
	std::array<float, 6> liftUnk11;
	EventNode liftUnk12;
	EventNode liftUnk13;
	EventNode liftUnk14;
	EventNode liftUnk15;
	EventNode liftUnk16;
	EventNode liftUnk17;
	void reflectMembers(MemberListener &r);
};

struct CKHkActivator : CKMRSubclass<CKHkActivator, CKHook, 52> {
	kobjref<CAnimationDictionary> actAnimDict;
	kobjref<CKSoundDictionaryID> actSndDict;
	kobjref<CKBoundingShape> actSphere1;
	kobjref<CKBoundingShape> actSphere2;
	float actUnk4;
	EventNode actEvtSeq1;
	EventNode actEvtSeq2;

	//void deserialize(KEnvironment* kenv, File *file, size_t length) override;
	//void serialize(KEnvironment* kenv, File *file) override;
	void reflectMembers(MemberListener &r);
};

struct CKHkRotaryBeam : CKMRSubclass<CKHkRotaryBeam, CKHook, 57> {
	kobjref<CKObject> rbAnimDict;
	kobjref<CKObject> rbSndDict;
	EventNode rbUnk2;
	EventNode rbUnk3;
	float rbUnk4;
	float rbUnk5;
	float rbUnk6;
	float rbUnk7;
	float rbUnk8;
	float rbUnk9;
	float rbUnk10;
	float rbUnk11;
	float rbUnk12;
	void reflectMembers2(MemberListener &r, KEnvironment* kenv);
};
struct CKHkLightPillar : CKMRSubclass<CKHkLightPillar, CKHook, 60> {
	void reflectMembers(MemberListener &r);
};
struct CKHkWind : CKMRSubclass<CKHkWind, CKHook, 73> {
	kobjref<CKObject> windSndDict;
	std::array<KPostponedRef<CKObject>, 2> windFogBoxes;
	float windUnk2;
	float windUnk3;
	float windUnk4;
	float windUnk5;
	Vector3 windUnk6;
	EventNode windUnk7;
	EventNode windUnk8;
	void reflectMembers(MemberListener &r);
};
struct CKHkPowderKeg : CKMRSubclass<CKHkPowderKeg, CKHook, 77> {
	KPostponedRef<CKObject> pkGround;
	kobjref<CKObject> pkCylinder;
	kobjref<CKObject> pkSndDict;
	kobjref<CKObject> pkUnk3;
	EventNode pkUnk4;
	EventNode pkUnk5;
	float pkUnk6;
	float pkUnk7;
	float pkUnk8;
	float pkUnk9;
	void reflectMembers(MemberListener &r);
};

struct CKHkEnemy : CKMRSubclass<CKHkEnemy, CKHook, 80> {
	uint32_t unk1;
	Vector3 unk2;
	float unk3;
	uint8_t unk4, unk5;
	kobjref<CKObject> squad;
	Vector3 unk7;
	float unk8;
	kobjref<CKObject> unk9;
	kobjref<CKObject> unkA;
	kobjref<CKObject> shadowCpnt;
	kobjref<CKObject> hkWaterFx;

	void deserialize(KEnvironment* kenv, File *file, size_t length) override;
	void serialize(KEnvironment* kenv, File *file) override;
	void reflectMembers2(MemberListener& r, KEnvironment* kenv);
};

struct CKHkSeizableEnemy : CKMRSubclass<CKHkSeizableEnemy, CKHkEnemy, 84> {
	uint32_t sunk1;
	uint8_t sunk2, sunk3, sunk4;
	std::array<kobjref<CKBoundingShape>, 4> boundingShapes;
	kobjref<CKSceneNode> particlesNodeFx1, particlesNodeFx2, particlesNodeFx3;
	kobjref<CKSceneNode> fogBoxNode;
	uint32_t sunused;
	kobjref<CKHook> hero;
	kobjref<CKSceneNode> romanAnimatedClone;
	uint8_t sunk5;
	std::array<float, 7> sunk6;

	void deserialize(KEnvironment* kenv, File *file, size_t length) override;
	void serialize(KEnvironment* kenv, File *file) override;
	void reflectMembers2(MemberListener& r, KEnvironment* kenv);
};

struct CKHkSquadEnemy : CKMRSubclass<CKHkSquadEnemy, CKHkEnemy, 88> {
	std::array<float, 9> matrix33;
	uint32_t hseUnk2;

	void deserialize(KEnvironment* kenv, File *file, size_t length) override;
	void serialize(KEnvironment* kenv, File *file) override;
	void reflectMembers2(MemberListener& r, KEnvironment* kenv);
};

struct CKHkSquadSeizableEnemy : CKMRSubclass<CKHkSquadSeizableEnemy, CKHkSeizableEnemy, 92> {
	std::array<float, 9> matrix33;
	uint32_t sunk7;

	void deserialize(KEnvironment* kenv, File *file, size_t length) override;
	void serialize(KEnvironment* kenv, File *file) override;
	void reflectMembers2(MemberListener& r, KEnvironment* kenv);
};

struct CKHkBasicEnemy : CKMRSubclass<CKHkBasicEnemy, CKHkSquadSeizableEnemy, 93> {
	kobjref<CKSceneNode> beClone1, beClone2, beClone3, beClone4;
	kobjref<CKSceneNode> beParticleNode1, beParticleNode2, beParticleNode3, beParticleNode4;
	kobjref<CAnimationDictionary> beAnimDict;
	kobjref<CKObject> beSoundDict;
	kobjref<CKBoundingShape> beBoundNode;

	kobjref<CAnimatedClone> romanAnimatedClone2;
	uint8_t beUnk1;
	std::array<float, 7> beUnk2;
	kobjref<CAnimatedClone> romanAnimatedClone3;
	uint8_t beUnk3;
	std::array<float, 7> beUnk4;
	float beUnk5, beUnk6;

	void deserialize(KEnvironment* kenv, File *file, size_t length) override;
	void serialize(KEnvironment* kenv, File *file) override;
	void reflectMembers2(MemberListener& r, KEnvironment* kenv);
};

struct CKHkAnimatedCharacter : CKMRSubclass<CKHkAnimatedCharacter, CKHook, 97> {
	kobjref<CAnimationDictionary> animDict;
	kobjref<CKObject> shadowCpnt;
	kobjref<CKObject> unkRef1;
	Matrix matrix;
	Vector3 position;
	Vector3 orientation;
	std::array<float, 7> unkFloatArray;
	float unkFloat1, unkFloat2, unkFloat3, unkFloat4;
	uint8_t sector;
	void reflectMembers(MemberListener& r);
};

struct CKHkSwingDoor : CKMRSubclass<CKHkSwingDoor, CKHook, 98> {
	kobjref<CKObject> swdSndDict;
	EventNode swdEvtSeq1;
	EventNode swdEvtSeq2;
	float swdUnk3;
	float swdUnk4;
	uint8_t swdUnk5;
	uint8_t swdUnk6;
	uint8_t swdUnk7;
	KPostponedRef<CKObject> swdNode1;
	KPostponedRef<CKObject> swdNode2;
	void reflectMembers(MemberListener &r);
};
struct CKHkSlideDoor : CKMRSubclass<CKHkSlideDoor, CKHook, 100> {
	kobjref<CKObject> sldSndDict;
	EventNode sldEvtSeq1;
	EventNode sldEvtSeq2;
	float sldUnk3;
	float sldUnk4;
	uint8_t sldUnk5;
	uint8_t sldUnk6;
	uint8_t sldUnk7;
	KPostponedRef<CKObject> sldNode;
	KPostponedRef<CKObject> sldDynGround;
	Vector3 sldUnk10;
	Vector3 sldUnk11;
	uint8_t sldRomasterValue = 0;
	void reflectMembers2(MemberListener &r, KEnvironment *kenv);
};
struct CKHkCrumblyZone : CKMRSubclass<CKHkCrumblyZone, CKHook, 102> {
	kobjref<CKObject> czSndDict;
	KPostponedRef<CKObject> czGround;
	kobjref<CKObject> czNode1;
	kobjref<CKObject> czNode2;
	kobjref<CKObject> czObb;
	kobjref<CKObject> czProjectileScrap;
	kobjref<CKObject> czParticleNode;
	float czUnk7;
	std::array<float, 2> czUnk8;
	uint16_t czEvtSeqMaybe;
	EventNode czEvtSeq2;
	void reflectMembers(MemberListener &r);
};
struct CKHkHelmetCage : CKMRSubclass<CKHkHelmetCage, CKHook, 108> {
	kobjref<CKObject> hcNode1;
	kobjref<CKObject> hcClone1;
	kobjref<CKObject> hcClone2;
	KPostponedRef<CKObject> hcDynGround1;
	KPostponedRef<CKObject> hcDynGround2;
	kobjref<CKObject> hcSndDict;
	float hcUnk6;
	float hcUnk7;
	float hcUnk8;
	float hcUnk9;
	float hcUnk10;
	float hcUnk11;
	float hcUnk12;
	float hcUnk13;
	float hcUnk14;
	float hcUnk15;
	kobjref<CKObject> hcObb1;
	kobjref<CKObject> hcObb2;
	void reflectMembers(MemberListener &r);
};
struct CKHkTeleBridge : CKMRSubclass<CKHkTeleBridge, CKHook, 111> {
	struct Part {
		kobjref<CKObject> mClone1;
		KPostponedRef<CKObject> mDynGround;
		kobjref<CKObject> mClone2;
		kobjref<CKObject> mClone3;
		void reflectMembers(MemberListener &r);
	};
	KPostponedRef<CKObject> tbStaticGround;
	kobjref<CKObject> tbSndDict;
	float tbUnk2;
	float tbUnk3;
	float tbUnk4;
	float tbUnk5;
	float tbUnk6;
	float tbUnk7;
	float tbUnk8;
	float tbUnk9;
	EventNode tbUnk10;
	EventNode tbUnk11;
	std::array<Part, 6> tbParts;
	void reflectMembers(MemberListener &r);
};
struct CKHkCrate : CKMRSubclass<CKHkCrate, CKHook, 112> {
	kobjref<CDynamicGround> ckhcUnk0;
	kobjref<CKCrateCpnt> ckhcUnk1;
	void reflectMembers2(MemberListener& r, KEnvironment* kenv);
};
struct CKHkBasicBonus : CKMRSubclass<CKHkBasicBonus, CKHook, 114> {
	kobjref<CKHkBasicBonus> nextBonus;
	kobjref<CKGrpBonusPool> pool;
	kobjref<CKObject> cpnt;
	kobjref<CKObject> hero;
	std::array<float, 7> somenums;

	void deserialize(KEnvironment* kenv, File *file, size_t length) override;
	void serialize(KEnvironment* kenv, File *file) override;
	void reflectMembers2(MemberListener& r, KEnvironment* kenv);
};

struct CKHkRollingStone : CKMRSubclass<CKHkRollingStone, CKHook, 126> {
	kobjref<CKFlaggedPath> rlstPath;
	kobjref<CKObject> rlstSphere;
	kobjref<CKObject> rlstProjScrap;
	kobjref<CKObject> rlstSndDict;
	kobjref<CKObject> rlstClone;
	float rlstUnk5;
	float rlstUnk6;
	float rlstUnk7;
	float rlstUnk8;
	float rlstUnk9;
	float rlstUnk10;
	float rlstUnk11;
	float rlstUnk12;
	float rlstUnk13;
	EventNode rlstUnk14;
	void reflectMembers(MemberListener &r);
	void onLevelLoaded(KEnvironment *kenv) override;
};

struct CKHkInterfaceBase : CKMRSubclass<CKHkInterfaceBase, CKHook, 128> {
	uint32_t uibFlags;
	kobjref<CKObject> uibGrpFrontEnd;
	void reflectMembers(MemberListener &r);
};
struct CKHkInterfaceEvolution : CKMRSubclass<CKHkInterfaceEvolution, CKHkInterfaceBase, 129> {
	std::array<kobjref<CKObject>, 8> ckhieUnk0;
	std::array<int32_t, 14> ckhieUnk1;
	void reflectMembers2(MemberListener& r, KEnvironment* kenv);
};
struct CKHkCatapult : CKMRSubclass<CKHkCatapult, CKHook, 130> {
	kobjref<CAnimationDictionary> ckhcUnk0;
	kobjref<CKSoundDictionaryID> ckhcUnk1;
	KPostponedRef<CDynamicGround> ckhcUnk2;
	kobjref<CAnimatedNode> ckhcUnk3;
	kobjref<CClone> ckhcUnk4;
	kobjref<CClone> ckhcUnk5;
	kobjref<CClone> ckhcUnk6;
	kobjref<CClone> ckhcUnk7;
	kobjref<CClone> ckhcUnk8;
	kobjref<CSGBranch> ckhcUnk9;
	uint8_t ckhcUnk10;
	kobjref<CKOBB> ckhcUnk11;
	Vector3 ckhcUnk12;
	float ckhcUnk13;
	Vector3 ckhcUnk14;
	Vector3 ckhcUnk15;
	uint8_t ckhcUnk16;
	uint8_t ckhcUnk17;
	uint8_t ckhcUnk18;
	float ckhcUnk19;
	float ckhcUnk20;
	float ckhcUnk21;
	Vector3 ckhcUnk22;
	float ckhcUnk23;
	float ckhcUnk24;
	float ckhcUnk25;
	float ckhcUnk26;
	float ckhcUnk27;
	float ckhcUnk28;
	float ckhcUnk29;
	kobjref<CNode> ckhcUnk30;
	float ckhcUnk31;
	kobjref<CParticlesNodeFx> ckhcUnk32;
	kobjref<CParticlesNodeFx> ckhcUnk33;
	kobjref<CParticlesNodeFx> ckhcUnk34;
	kobjref<CParticlesNodeFx> ckhcUnk35;
	kobjref<CParticlesNodeFx> ckhcUnk36;
	kobjref<CKGrpCatapult> ckhcUnk37;
	uint8_t ckhcUnk38;
	uint8_t ckhcUnk39;
	uint8_t ckhcUnk40;
	kobjref<CKProjectileTypeScrap> ckhcUnk41;
	kobjref<CKHkWaterFx> ckhcUnk42;
	void reflectMembers2(MemberListener& r, KEnvironment* kenv);
};
struct CKHkInterfacePause : CKMRSubclass<CKHkInterfacePause, CKHkInterfaceBase, 131> {
	kobjref<CColorTextButton2d> ckhipUnk0;
	kobjref<CColorTextButton2d> ckhipUnk1;
	kobjref<CColorTextButton2d> ckhipUnk2;
	kobjref<CColorTextButton2d> ckhipUnk3;
	kobjref<CColorTextButton2d> ckhipUnk4;
	kobjref<CBillboard2d> ckhipUnk5;
	void reflectMembers2(MemberListener& r, KEnvironment* kenv);
};
struct CKHkInterfaceInGame : CKMRSubclass<CKHkInterfaceInGame, CKHkInterfaceBase, 132> {
	std::array<kobjref<CKObject>, 31> uiigShields;
	std::array<kobjref<CKObject>, 3> uiigUnk1;
	std::array<kobjref<CKObject>, 2> uiigUnk2;
	std::array<kobjref<CKObject>, 2> uiigUnk3;
	std::array<kobjref<CKObject>, 17> uiigUnk4;
	std::array<kobjref<CKObject>, 5> uiigUnk5;
	std::array<kobjref<CKObject>, 7> uiigTextBoxes;
	kobjref<CKObject> uiigSndDict;
	std::array<uint32_t, 13> uiigUnk8;
	std::array<uint32_t, 13> uiigActionTextIDs;
	uint32_t uiigUnk10;
	std::array<float, 9> uiigUnk11;
	std::array<float, 11> uiigShieldValues;
	std::array<float, 5> uiigPotionValues;
	std::array<float, 6> uiigUnk14;
	uint8_t uiigUnk15;
	std::array<float, 2> uiigUnk16;
	std::array<float, 11> uiigHelmetValues;
	std::array<float, 2> uiigUnk18;
	std::array<float, 5> uiigUnk19;
	std::array<float, 2> uiigUnk20;
	std::array<float, 5> uiigLaurelValues;
	std::array<kobjref<CKObject>, 2> uiigUnk22;
	std::array<kobjref<CKObject>, 2> uiigUnk23;
	std::array<kobjref<CKObject>, 7> uiigUnk24;
	std::array<kobjref<CKObject>, 2> uiigUnk25;
	float uiigUnk26;
	float uiigUnk27;
	float uiigUnk28;
	float uiigUnk29;
	float uiigUnk30;
	void reflectMembers(MemberListener &r);
};

struct CKHkInterfaceOption : CKMRSubclass<CKHkInterfaceOption, CKHkInterfaceBase, 133> {
	std::array<kobjref<CKObject>, 5> uiioptUnk0;
	std::vector<kobjref<CKObject>> uiioptUnk1;
	uint32_t uiioptUnk2;
	uint32_t uiioptUnk3;
	uint32_t uiioptUnk4;
	uint32_t uiioptUnk5;
	uint32_t uiioptUnk6;
	uint32_t uiioptUnk7;
	uint32_t uiioptUnk8;
	uint32_t uiioptUnk9;
	uint32_t uiioptUnk10;
	uint32_t uiioptUnk11;
	uint32_t uiioptUnk12;
	uint32_t uiioptUnk13;
	uint32_t uiioptUnk14;
	uint32_t uiioptUnk15;
	uint32_t uiioptUnk16;
	uint32_t uiioptUnk17;
	uint32_t uiioptUnk18;
	std::array<kobjref<CKObject>, 5> uiioptUnk19;
	uint32_t uiioptUnk20;
	std::array<kobjref<CKObject>, 11> uiioptUnk21;
	std::array<kobjref<CKObject>, 4> uiioptUnk22;
	std::array<kobjref<CKObject>, 23> uiioptUnk23;
	std::array<kobjref<CKObject>, 23> uiioptUnk24;
	std::array<uint32_t, 3> uiioptUnk25;
	std::array<kobjref<CKObject>, 3> uiioptUnk26;
	kobjref<CKObject> uiioptUnk27;
	kobjref<CKObject> uiioptUnk28;
	std::array<uint32_t, 3> uiioptUnk29;
	std::array<kobjref<CKObject>, 3> uiioptUnk30;
	uint32_t uiioptUnk31;
	kobjref<CKObject> uiioptUnk32;
	kobjref<CKObject> uiioptUnk33;
	uint32_t uiioptUnk34;
	uint32_t uiioptUnk35;
	uint32_t uiioptUnk36;
	uint32_t uiioptUnk37;
	uint32_t uiioptUnk38;
	uint32_t uiioptUnk39;
	kobjref<CKObject> uiioptUnk40;
	kobjref<CKObject> uiioptUnk41;
	uint32_t uiioptUnk42 = 1037;
	uint32_t uiioptUnk43 = 1043;
	kobjref<CKObject> uiioptUnk44;
	kobjref<CKObject> uiioptUnk45;
	std::array<uint32_t, 3> uiioptUnk46 = { 1055, 1056, 1057 };
	uint32_t uiioptUnk47 = 1058;
	void reflectMembers2(MemberListener &r, KEnvironment *kenv);
};
struct CKHkInterfaceMain : CKMRSubclass<CKHkInterfaceMain, CKHkInterfaceBase, 136> {
	kobjref<CKSoundDictionaryID> ckhimUnk0;
	kobjref<CBillboard2d> ckhimUnk1;
	kobjref<CBillboard2d> ckhimUnk2;
	kobjref<CColorTextButton2d> ckhimUnk3;
	kobjref<CColorTextButton2d> ckhimUnk4;
	kobjref<CColorTextButton2d> ckhimUnk5;
	kobjref<CColorTextButton2d> ckhimUnk6;
	kobjref<CText2d> ckhimUnk7;
	kobjref<CText2d> ckhimUnk8;
	kobjref<CText2d> ckhimUnk9;
	std::array<float, 2> ckhimUnk10;
	kobjref<CBillboard2d> ckhimUnk11;
	kobjref<CText2d> ckhimUnk12;
	kobjref<CColorTextButton2d> ckhimUnk13;
	int32_t ckhimUnk14;
	void reflectMembers2(MemberListener& r, KEnvironment* kenv);
};
struct CKHkInterfaceLoadSave : CKMRSubclass<CKHkInterfaceLoadSave, CKHkInterfaceBase, 138> {
	std::array<kobjref<CKObject>, 3> ckhilsUnk0;
	kobjref<CText2d> ckhilsUnk1;
	std::array<kobjref<CKObject>, 5> ckhilsUnk2;
	std::array<kobjref<CKObject>, 6> ckhilsUnk3;
	std::array<kobjref<CKObject>, 3> ckhilsUnk4;
	std::array<kobjref<CKObject>, 2> ckhilsUnk5;
	std::array<float, 3> ckhilsUnk6;
	std::array<int32_t, 6> ckhilsUnk7;
	std::array<int32_t, 4> ckhilsUnk8;
	std::array<int32_t, 7> ckhilsUnk9;
	kobjref<CBillboard2d> ckhilsUnk10;
	kobjref<CBillboard2d> ckhilsUnk11;
	void reflectMembers2(MemberListener& r, KEnvironment* kenv);
};
struct CKHkInterfaceCloth : CKMRSubclass<CKHkInterfaceCloth, CKHkInterfaceBase, 141> {
	std::array<kobjref<CKObject>, 16> ckhicUnk0;
	std::array<float, 6> ckhicUnk1;
	std::array<float, 3> ckhicUnk2;
	std::array<float, 12> ckhicUnk3;
	std::array<int32_t, 2> ckhicUnk4;
	std::array<int32_t, 8> ckhicUnk5;
	int32_t ckhicUnk6;
	int32_t ckhicUnk7;
	int32_t ckhicUnk8;
	int32_t ckhicUnk9;
	void reflectMembers2(MemberListener& r, KEnvironment* kenv);
};
struct CKHkPushPullAsterix : CKMRSubclass<CKHkPushPullAsterix, CKHook, 147> {
	struct Special {
		float mUnk0;
		float mUnk1;
		float mUnk2;
		float mUnk3;
		float mUnk4;
		float mUnk5;
		float mUnk6;
		kobjref<CKObject> mSndDict;
		void reflectMembers(MemberListener &r);
	};
	uint16_t ppaUnk0;
	Vector3 ppaUnk1;
	Vector3 ppaUnk2;
	Vector3 ppaUnk3;
	Vector3 ppaUnk4;
	float ppaUnk5;
	float ppaUnk6;
	float ppaUnk7;
	float ppaUnk8;
	float ppaUnk9;
	float ppaUnk10;
	float ppaUnk11;
	float ppaUnk12;
	kobjref<CKObject> ppaFlaggedPath;
	kobjref<CKObject> ppaLine;
	float ppaUnk15;
	float ppaUnk16;
	float ppaUnk17;
	float ppaUnk18;
	float ppaUnk19;
	float ppaUnk20;
	float ppaUnk21;
	kobjref<CKObject> ppaObb;
	float ppaUnk23;
	float ppaUnk24;
	float ppaUnk25;
	Special ppaUnk26;
	kobjref<CKObject> ppaParticleNode1;
	kobjref<CKObject> ppaParticleNode2;
	float ppaUnk29;
	kobjref<CKObject> ppaSndDict;
	KPostponedRef<CKObject> ppaDynGround;
	EventNode ppaUnk32;
	EventNode ppaUnk33;
	EventNode ppaUnk34;
	EventNode ppaUnk35;
	Vector3 ppaUnk36;
	float ppaUnk37;
	float ppaUnk38;
	kobjref<CKObject> ppaBranch1;
	kobjref<CKObject> ppaBranch2;
	kobjref<CKObject> ppaBranch3;
	kobjref<CKObject> ppaBranch4;
	MarkerIndex ppaUnk43;
	MarkerIndex ppaUnk44;
	void reflectMembers(MemberListener &r);
	void onLevelLoaded(KEnvironment *kenv) override;
};
struct CKHkTelepher : CKMRSubclass<CKHkTelepher, CKHook, 158> {
	kobjref<CKObject> telUnk0;
	float telUnk1;
	kobjref<CKObject> telUnk2;
	kobjref<CKObject> telUnk3;
	kobjref<CKObject> telFlaggedPath;
	KPostponedRef<CKObject> telDynGround;
	MarkerIndex telUnk6;
	float telUnk7;
	float telUnk8;
	float telUnk9;
	float telUnk10;
	float telUnk11;
	float telUnk12;
	float telUnk13;
	float telUnk14;
	float telUnk15;
	int32_t telUnk16;
	float telUnk17;
	float telUnk18;
	float telUnk19;
	float telUnk20;
	EventNode telUnk21;
	kobjref<CKObject> telSndDict;
	void reflectMembers(MemberListener &r);
};
struct CKHkTowedTelepher : CKMRSubclass<CKHkTowedTelepher, CKHkTelepher, 159> {
	kobjref<CKObject> towtelTowNode1;
	kobjref<CKObject> towtelTowNode2;
	kobjref<CKObject> towtelParticleNode;
	float towtelUnk3;
	float towtelUnk4;
	float towtelUnk5;
	float towtelUnk6;
	float towtelUnk7;
	float towtelUnk8;
	float towtelUnk9;
	float towtelUnk10;
	float towtelUnk11;
	kobjref<CKObject> towtelSphere;
	Matrix towtelUnk13;
	EventNode towtelUnk14;
	EventNode towtelUnk15;
	void reflectMembers(MemberListener &r);
};
struct CKHkBumper : CKMRSubclass<CKHkBumper, CKHook, 160> {
	kobjref<CKObject> bmpBranch;
	kobjref<CKObject> bmpAnimnode;
	kobjref<CKObject> bmpAnimDict;
	kobjref<CKObject> bmpSndDict;
	kobjref<CKObject> bmpObb;
	KPostponedRef<CKObject> bmpGround;
	EventNode bmpUnk6;
	float bmpUnk7;
	float bmpUnk8;
	float bmpUnk9;
	uint8_t bmpUnk10;
	void reflectMembers2(MemberListener &r, KEnvironment* kenv);
};

struct CKHkClueMan : CKMRSubclass<CKHkClueMan, CKHook, 161> {
	struct Ing {
		uint8_t mUnk0;
		kobjref<CKObject> mCamera;
		float mUnk2;
		float mUnk3;
		void reflectMembers(MemberListener &r);
	};
	uint8_t cmUnk0;
	uint8_t cmUnk1;
	float cmUnk2;
	float cmUnk3;
	float cmUnk4;
	int32_t cmUnk5;
	int32_t cmUnk6;
	int32_t cmUnk7;
	// uint16_t sizeFor_cmBings;
	std::vector<Ing> cmBings;
	// uint16_t sizeFor_cmDings;
	std::vector<Ing> cmDings;
	// uint16_t sizeFor_cmFings;
	std::vector<Ing> cmFings;
	int32_t cmUnk14;
	int32_t cmUnk15;
	int32_t cmUnk16;
	int32_t cmUnk17;
	int32_t cmUnk18;
	EventNode cmUnk19;
	EventNode cmUnk20;
	EventNode cmUnk21;
	EventNode cmUnk22;
	EventNode cmUnk23;
	uint8_t cmUnk24;
	uint8_t cmUnk25;
	uint8_t cmUnk26;
	uint8_t cmUnk27;
	uint8_t cmUnk28;
	uint8_t cmUnk29;
	uint8_t cmUnk30;
	kobjref<CKObject> cmUnk31;
	kobjref<CKObject> cmUnk32;
	kobjref<CKObject> cmUnk33;
	kobjref<CKObject> cmUnk34;
	kobjref<CKObject> cmUnk35;
	kobjref<CKObject> cmUnk36;
	uint8_t cmUnk37;
	kobjref<CKObject> cmBillboard1;
	kobjref<CKObject> cmBillboard2;
	Vector3 cmUnk40;
	float cmUnk41;
	float cmUnk42;
	float cmUnk43;
	float cmUnk44;
	Vector3 cmUnk45;
	float cmUnk46;
	float cmUnk47;
	float cmUnk48;
	float cmUnk49;
	float cmUnk50;
	float cmUnk51;
	float cmUnk52;
	float cmUnk53;
	float cmUnk54;
	float cmUnk55;
	float cmUnk56;
	float cmUnk57;
	float cmUnk58;
	Vector3 cmUnk59;
	float cmUnk60;
	void reflectMembers(MemberListener &r);
};
struct CKHkSky : CKMRSubclass<CKHkSky, CKHook, 163> {
	void reflectMembers(MemberListener &r);
};

struct CKHkRocketRoman : CKMRSubclass<CKHkRocketRoman, CKHkBasicEnemy, 164> {
	kobjref<CKObject> rrAnimDict, rrParticleNode, rrCylinderNode, rrSoundDictID;

	void deserialize(KEnvironment* kenv, File *file, size_t length) override;
	void serialize(KEnvironment* kenv, File *file) override;
};

struct CKHkJetPackRoman : CKMRSubclass<CKHkJetPackRoman, CKHkSquadEnemy, 167> {
	std::array<kobjref<CKObject>, 8> hjpUnk0;
	uint8_t hjpUnk1;
	std::array<float, 7> hjpUnk2;
	kobjref<CKObject> hjpUnk3;
	uint8_t hjpUnk4;
	std::array<float, 7> hjpUnk5;
	kobjref<CKObject> hjpUnk6;
	kobjref<CKObject> hjpUnk7;
	kobjref<CKObject> hjpUnk8;

	void deserialize(KEnvironment* kenv, File *file, size_t length) override;
	void serialize(KEnvironment* kenv, File *file) override;
};

struct CKHkWildBoar : CKMRSubclass<CKHkWildBoar, CKHook, 171> {
	kobjref<CKHkWildBoar> nextBoar;
	kobjref<CKSceneNode> boundingSphere;
	kobjref<CKObject> animationDictionary;
	kobjref<CKObject> cpnt;
	kobjref<CKGrpWildBoarPool> pool;
	std::array<float, 4> somenums;
	kobjref<CKObject> shadowCpnt;

	void deserialize(KEnvironment* kenv, File *file, size_t length) override;
	void serialize(KEnvironment* kenv, File *file) override;
};

struct CKHkAsterixShop : CKMRSubclass<CKHkAsterixShop, CKHook, 172> {
	kobjref<CKObject> shopAnimNode2;
	kobjref<CKObject> shopAnimDict1;
	kobjref<CKObject> shopAnimDict2;
	kobjref<CKObject> shopSndDict;
	kobjref<CKObject> shopBillboardList;
	kobjref<CKObject> shopText1;
	kobjref<CKObject> shopText2;
	kobjref<CKObject> shopText3;
	kobjref<CKObject> shopText4;
	kobjref<CKObject> shopBillboard1;
	kobjref<CKObject> shopBillboard2;
	std::array<float, 8> shopUnk11;
	std::array<uint32_t, 2> shopUnk12;
	uint32_t shopUnk13;
	std::array<uint32_t, 6> shopUnk14;
	std::array<uint32_t, 14> shopUnk15;
	std::array<uint32_t, 10> shopUnk16;
	std::array<uint32_t, 12> shopUnk17;
	std::array<uint8_t, 3> shopUnk18;
	kobjref<CKObject> shopCameraTrack;
	Vector3 shopUnk20;
	Vector3 shopUnk21;
	float shopUnk22;
	float shopUnk23;
	float shopUnk24;
	kobjref<CKObject> shopDynGround;
	Vector3 shopUnk26;
	Vector3 shopUnk27;
	float shopUnk28;
	float shopUnk29;
	float shopUnk30;
	float shopUnk31;
	void reflectMembers(MemberListener &r);
};

struct CKHkWater : CKMRSubclass<CKHkWater, CKHook, 173> {
	kobjref<CNode> ckhwUnk0;
	kobjref<CKHkWaterFx> ckhwUnk1;
	float ckhwSizeX;
	float ckhwSizeZ;
	float ckhwUnk4;
	float ckhwUnk5;
	uint8_t ckhwUnk6;
	uint8_t ckhwUnk7;
	uint8_t ckhwUnk8;
	uint8_t ckhwUnk9;
	std::string ckhwUnk10;
	std::string ckhwUnk11;
	float ckhwUnk12;
	int32_t ckhwUnk13;
	uint8_t ckhwUnk14;
	float ckhwUnk15;
	float ckhwUnk16;
	float ckhwUnk17;
	uint8_t ckhwUnk18;
	uint8_t ckhwUnk19;
	uint8_t ckhwUnk20;
	uint8_t ckhwUnk21;
	uint8_t ckhwUnk22;
	uint8_t ckhwUnk23;
	uint8_t ckhwUnk24;
	//int32_t ckhwUnk25;
	std::vector<KPostponedRef<CGround>> ckhwGrounds;
	int32_t ckhwSectorsBitArray;
	uint8_t ckhwUnk30;
	struct WaterDing {
		uint8_t wdUnk1;
		kobjref<CNode> wdNode; // if wdUnk1==0
		kobjref<CKHkWater> wdUnk2;
		std::string wdUnk3;
		float wdUnk4;
		float wdUnk5;
	};
	std::array<WaterDing, 2> ckhwDings;
	void reflectMembers2(MemberListener& r, KEnvironment* kenv);
};

struct CKHkMobileTower : CKMRSubclass<CKHkMobileTower, CKHkSquadEnemy, 176> {
	struct Part {
		kobjref<CKObject> obj;
		uint8_t byteVal;
		std::array<float, 7> fltValues;
	};
	std::array<kobjref<CKObject>, 19> hmtObjs1;
	uint8_t hmtUnk1;
	std::array<float, 7> hmtUnk2;
	std::array<Part, 4> parts;
	std::array<kobjref<CKObject>, 22> hmtObjs2;
	std::array<float, 7> hmtUnk5;
	kobjref<CKObject> hmtUnk6;

	void deserialize(KEnvironment* kenv, File *file, size_t length) override;
	void serialize(KEnvironment* kenv, File *file) override;
};

struct CKHkWaterFx : CKMRSubclass<CKHkWaterFx, CKHook, 180> {
	uint8_t ckhwfUnk0;
	uint8_t ckhwfUnk1;
	uint8_t ckhwfUnk2;
	uint8_t ckhwfUnk3;
	kobjref<CSGBranch> ckhwfUnk4;
	kobjref<CNode> ckhwfUnk5;
	std::string ckhwfUnk6;
	kobjref<CNode> ckhwfUnk7;
	kobjref<CNode> ckhwfUnk8;
	kobjref<CNode> ckhwfUnk9;
	kobjref<CNode> ckhwfUnk10;
	kobjref<CNode> ckhwfUnk11;
	kobjref<CNode> ckhwfUnk12;
	kobjref<CNode> ckhwfUnk13;
	kobjref<CNode> ckhwfUnk14;
	kobjref<CNode> ckhwfUnk15;
	kobjref<CNode> ckhwfUnk16;
	kobjref<CParticlesNodeFx> ckhwfUnk17;
	kobjref<CParticlesNodeFx> ckhwfUnk18;
	float ckhwfUnk19;
	float ckhwfUnk20;
	float ckhwfUnk21;
	float ckhwfUnk22;
	float ckhwfUnk23;
	float ckhwfUnk24;
	float ckhwfUnk25;
	float ckhwfUnk26;
	float ckhwfUnk27;
	float ckhwfUnk28;
	float ckhwfUnk29;
	float ckhwfUnk30;
	float ckhwfUnk31;
	float ckhwfUnk32;
	float ckhwfUnk33;
	std::array<std::array<float, 3>, 10> ckhwfValueArray;
	float ckhwfUnk64;
	float ckhwfUnk65;
	float ckhwfUnk66;
	float ckhwfUnk67;
	float ckhwfUnk68;
	float ckhwfUnk69;
	float ckhwfUnk70;
	float ckhwfUnk71;
	int32_t ckhwfUnk72;
	int32_t ckhwfUnk73;
	int32_t ckhwfUnk74;
	int32_t ckhwfUnk75;
	float ckhwfUnk76;
	float ckhwfUnk77;
	float ckhwfUnk78;
	float ckhwfUnk79;
	float ckhwfUnk80;
	float ckhwfUnk81;
	float ckhwfUnk82;
	float ckhwfUnk83;
	kobjref<CParticlesNodeFx> ckhwfUnk84;
	float ckhwfUnk85;
	float ckhwfUnk86;
	float ckhwfUnk87;
	float ckhwfUnk88;
	float ckhwfUnk89;
	float ckhwfUnk90;
	float ckhwfUnk91;
	float ckhwfUnk92;
	void reflectMembers2(MemberListener& r, KEnvironment* kenv);
};

struct CKHkHighGrass : CKMRSubclass<CKHkHighGrass, CKHook, 183> {};

struct CKHkWaterFall : CKMRSubclass<CKHkWaterFall, CKHook, 185> {
	kobjref<CKObject> wfallBranch2;
	float wfallUnk1;
	float wfallUnk2;
	void reflectMembers(MemberListener &r);
};
struct CKHkInterfaceGallery : CKMRSubclass<CKHkInterfaceGallery, CKHkInterfaceBase, 187> {
	kobjref<CBillboard2d> ckhigUnk0;
	kobjref<CBillboard2d> ckhigUnk1;
	kobjref<CBillboard2d> ckhigUnk2;
	kobjref<CBillboard2d> ckhigUnk3;
	kobjref<CText2d> ckhigUnk4;
	kobjref<CText2d> ckhigUnk5;
	kobjref<CText2d> ckhigUnk6;
	kobjref<CText2d> ckhigUnk7;
	kobjref<CText2d> ckhigUnk8;
	kobjref<CText2d> ckhigUnk9;
	kobjref<CNode> ckhigUnk10;
	kobjref<CKSoundDictionaryID> ckhigUnk11;
	kobjref<CColorTextButton2d> ckhigUnk12;
	kobjref<CColorTextButton2d> ckhigUnk13;
	std::array<int32_t, 11> ckhigUnk14;
	int32_t ckhigUnk15;
	int32_t ckhigUnk16;
	std::array<int32_t, 6> ckhigUnk17;
	int32_t ckhigUnk18;
	int32_t ckhigUnk19;
	std::array<int32_t, 44> ckhigUnk20;
	std::array<int32_t, 2> ckhigUnk21;
	std::array<float, 2> ckhigUnk22;
	void reflectMembers2(MemberListener& r, KEnvironment* kenv);
};
struct CKHkInterfaceOpening : CKMRSubclass<CKHkInterfaceOpening, CKHkInterfaceBase, 192> {
	std::array<kobjref<CKObject>, 7> ckhioUnk0;
	std::array<int32_t, 5> ckhioUnk1;
	float ckhioUnk2;
	kobjref<CBillboard2d> ckhioUnk3;
	int32_t ckhioUnk4;
	kobjref<CBillboard2d> ckhioUnk5;
	kobjref<CText2d> ckhioUnk6;
	kobjref<CBillboard2d> ckhioNintendo;
	void reflectMembers2(MemberListener& r, KEnvironment* kenv);
};
struct CKHkAsterixCheckpoint : CKMRSubclass<CKHkAsterixCheckpoint, CKHook, 193> {
	kobjref<CKObject> acpNode;
	kobjref<CKObject> acpAnimDict;
	kobjref<CKObject> acpSndDict;
	kobjref<CKObject> acpSphere1;
	kobjref<CKObject> acpSphere2;
	kobjref<CKObject> acpSphere3;
	kobjref<CKObject> acpParticleNode1;
	kobjref<CKObject> acpParticleNode2;
	kobjref<CKObject> acpGrpCheckpoint;
	Vector3 acpUnk9;
	void reflectMembers(MemberListener &r);
};
struct CKHkBonusSpitter : CKMRSubclass<CKHkBonusSpitter, CKHook, 194> {
	KPostponedRef<CKObject> bsDynGround;
	KPostponedRef<CKObject> bsNode;
	float bsUnk2;
	float bsUnk3;
	float bsUnk4;
	uint32_t bsBonusType;
	void reflectMembers(MemberListener &r);
};
struct CKHkLight : CKMRSubclass<CKHkLight, CKHook, 195> {
	kobjref<CKObject> lightGrpLight;
	EventNode lightEvtSeq1;
	EventNode lightEvtSeq2;
	EventNode lightEvtSeq3;
	EventNode lightEvtSeq4;
	void reflectMembers(MemberListener &r);
};

struct CKHkParkourSteleAsterix : CKMRSubclass<CKHkParkourSteleAsterix, CKHook, 214> {
	uint16_t parkUnk0;
	Vector3 parkUnk1;
	float parkTimeLimit;
	float parkUnk3;
	uint16_t parkUnk4;
	Vector3 parkUnk5;
	uint8_t parkUnk6;
	uint16_t parkUnk7;
	uint16_t parkUnk8;
	kobjref<CKSceneNode> parkNode1;
	kobjref<CKSceneNode> parkNode2;
	uint8_t parkUnk11;
	uint8_t parkGameType; // 0=coin, 1=time attack
	float parkBronzeTime;
	float parkSilverTime;
	float parkGoldTime;
	uint8_t parkId;
	void reflectMembers(MemberListener& r);
};

struct CKHkJumpingRoman : CKMRSubclass<CKHkJumpingRoman, CKHkSquadSeizableEnemy, 75> {
	kobjref<CClone> ckhjrUnk31;
	kobjref<CClone> ckhjrUnk32;
	kobjref<CKObject> ckhjrUnk33;
	uint8_t ckhjrUnk34;
	std::array<float, 7> ckhjrUnk35;
	kobjref<CKObject> ckhjrUnk36;
	uint8_t ckhjrUnk37;
	std::array<float, 7> ckhjrUnk38;
	kobjref<CAnimationDictionary> ckhjrUnk39;
	kobjref<CKSoundDictionaryID> ckhjrUnk40;
	kobjref<CKBoundingSphere> ckhjrUnk41;
	float ckhjrUnk42;
	float ckhjrUnk43;
	float ckhjrUnk44;
	int32_t ckhjrUnk45;
	void reflectMembers2(MemberListener& r, KEnvironment* kenv);
};

struct CKHkTurtle : CKMRSubclass<CKHkTurtle, CKHkSquadEnemy, 88> {
	kobjref<CAnimationDictionary> ckhptUnk17;
	kobjref<CAnimationDictionary> ckhptUnk18;
	kobjref<CAnimationDictionary> ckhptUnk19;
	kobjref<CKSoundDictionaryID> ckhptUnk20;
	kobjref<CAnimatedClone> ckhptUnk21;
	kobjref<CAnimatedClone> ckhptUnk22;
	kobjref<CDynamicGround> ckhptUnk23;
	kobjref<CParticlesNodeFx> ckhptUnk24;
	kobjref<CParticlesNodeFx> ckhptUnk25;
	kobjref<CParticlesNodeFx> ckhptUnk26;
	std::array<float, 3> ckhptUnk27;
	std::array<float, 3> ckhptUnk28;
	std::array<float, 3> ckhptUnk29;
	std::array<float, 3> ckhptUnk30;
	std::array<float, 3> ckhptUnk31;
	std::array<float, 3> ckhptUnk32;
	std::array<float, 3> ckhptUnk33;
	std::array<float, 3> ckhptUnk34;
	std::array<float, 3> ckhptUnk35;
	uint16_t ckhptUnk36;
	uint16_t ckhptUnk37;
	EventNode ckhptUnk38;
	EventNode ckhptUnk39;
	kobjref<CKProjectileTypeScrap> ckhptUnk40;
	kobjref<CKProjectileTypeScrap> ckhptUnk41;
	void reflectMembers2(MemberListener& r, KEnvironment* kenv);
};

struct CKHkPyramidalTurtle : CKMRSubclass<CKHkPyramidalTurtle, CKHkTurtle, 125> {
	kobjref<CKOBB> ckhptUnk0;
	kobjref<CKOBB> ckhptUnk1;
	kobjref<CKOBB> ckhptUnk2;
	kobjref<CKOBB> ckhptUnk3;
	kobjref<CKOBB> ckhptUnk4;
	kobjref<CKOBB> ckhptUnk5;
	kobjref<CKOBB> ckhptUnk6;
	kobjref<CKOBB> ckhptUnk7;
	kobjref<CKOBB> ckhptUnk8;
	kobjref<CKOBB> ckhptUnk9;
	kobjref<CKOBB> ckhptUnk10;
	kobjref<CKOBB> ckhptUnk11;
	kobjref<CKOBB> ckhptUnk12;
	kobjref<CKOBB> ckhptUnk13;
	kobjref<CKOBB> ckhptUnk14;
	kobjref<CKBoundingSphere> ckhptUnk15;
	float ckhptUnk16;
	float ckhptUnk17;
	float ckhptUnk18;
	float ckhptUnk19;
	float ckhptUnk20;
	float ckhptUnk21;
	float ckhptUnk22;
	float ckhptUnk23;
	float ckhptUnk24;
	float ckhptUnk25;
	float ckhptUnk26;
	float ckhptUnk27;
	float ckhptUnk28;
	float ckhptUnk29;
	float ckhptUnk30;
	float ckhptUnk31;
	float ckhptUnk32;
	float ckhptUnk33;
	float ckhptUnk34;
	float ckhptUnk35;
	float ckhptUnk36;
	float ckhptUnk37;
	float ckhptUnk38;
	float ckhptUnk39;
	float ckhptUnk40;
	float ckhptUnk41;
	float ckhptUnk42;
	float ckhptUnk43;
	float ckhptUnk44;
	float ckhptUnk45;
	float ckhptUnk46;
	float ckhptUnk47;
	float ckhptUnk48;
	float ckhptUnk49;
	float ckhptUnk50;
	float ckhptUnk51;
	float ckhptUnk52;
	float ckhptUnk53;
	float ckhptUnk54;
	float ckhptUnk55;
	float ckhptUnk56;
	float ckhptUnk57;
	float ckhptUnk58;
	float ckhptUnk59;
	float ckhptUnk60;
	float ckhptUnk61;
	float ckhptUnk62;
	float ckhptUnk63;
	float ckhptUnk64;
	float ckhptUnk65;
	float ckhptUnk66;
	float ckhptUnk67;
	float ckhptUnk68;
	float ckhptUnk69;
	kobjref<CAnimatedClone> ckhptUnk70;
	kobjref<CAnimatedClone> ckhptUnk71;
	kobjref<CAnimatedClone> ckhptUnk72;
	kobjref<CAnimatedClone> ckhptUnk73;
	kobjref<CAnimatedClone> ckhptUnk74;
	kobjref<CAnimatedClone> ckhptUnk75;
	kobjref<CAnimatedClone> ckhptUnk76;
	kobjref<CAnimatedClone> ckhptUnk77;
	kobjref<CAnimatedClone> ckhptUnk78;
	kobjref<CAnimationDictionary> ckhptUnk79;
	void reflectMembers2(MemberListener& r, KEnvironment* kenv);
};

struct CKHkSquareTurtle : CKMRSubclass<CKHkSquareTurtle, CKHkTurtle, 110> {
	kobjref<CKOBB> ckhstUnk0;
	kobjref<CKOBB> ckhstUnk1;
	kobjref<CKOBB> ckhstUnk2;
	kobjref<CKOBB> ckhstUnk3;
	kobjref<CKOBB> ckhstUnk4;
	kobjref<CKOBB> ckhstUnk5;
	kobjref<CKOBB> ckhstUnk6;
	kobjref<CKBoundingSphere> ckhstUnk7;
	float ckhstUnk8;
	float ckhstUnk9;
	float ckhstUnk10;
	float ckhstUnk11;
	float ckhstUnk12;
	float ckhstUnk13;
	float ckhstUnk14;
	float ckhstUnk15;
	float ckhstUnk16;
	float ckhstUnk17;
	float ckhstUnk18;
	float ckhstUnk19;
	float ckhstUnk20;
	float ckhstUnk21;
	float ckhstUnk22;
	float ckhstUnk23;
	float ckhstUnk24;
	float ckhstUnk25;
	float ckhstUnk26;
	float ckhstUnk27;
	float ckhstUnk28;
	float ckhstUnk29;
	float ckhstUnk30;
	float ckhstUnk31;
	float ckhstUnk32;
	float ckhstUnk33;
	float ckhstUnk34;
	float ckhstUnk35;
	float ckhstUnk36;
	float ckhstUnk37;
	kobjref<CAnimatedClone> ckhstUnk38;
	kobjref<CAnimatedClone> ckhstUnk39;
	kobjref<CAnimatedClone> ckhstUnk40;
	kobjref<CAnimatedClone> ckhstUnk41;
	kobjref<CAnimatedClone> ckhstUnk42;
	void reflectMembers2(MemberListener& r, KEnvironment* kenv);
};

struct CKHkDonutTurtle : CKMRSubclass<CKHkDonutTurtle, CKHkTurtle, 124> {
	kobjref<CKOBB> ckhdtUnk0;
	kobjref<CKOBB> ckhdtUnk1;
	kobjref<CKOBB> ckhdtUnk2;
	kobjref<CKOBB> ckhdtUnk3;
	kobjref<CKOBB> ckhdtUnk4;
	kobjref<CKOBB> ckhdtUnk5;
	kobjref<CKOBB> ckhdtUnk6;
	kobjref<CKOBB> ckhdtUnk7;
	kobjref<CKOBB> ckhdtUnk8;
	kobjref<CKOBB> ckhdtUnk9;
	kobjref<CKOBB> ckhdtUnk10;
	kobjref<CKOBB> ckhdtUnk11;
	kobjref<CKOBB> ckhdtUnk12;
	kobjref<CKOBB> ckhdtUnk13;
	kobjref<CKOBB> ckhdtUnk14;
	kobjref<CKOBB> ckhdtUnk15;
	kobjref<CKOBB> ckhdtUnk16;
	kobjref<CKOBB> ckhdtUnk17;
	kobjref<CKOBB> ckhdtUnk18;
	kobjref<CKOBB> ckhdtUnk19;
	kobjref<CKOBB> ckhdtUnk20;
	kobjref<CKOBB> ckhdtUnk21;
	kobjref<CKOBB> ckhdtUnk22;
	kobjref<CKOBB> ckhdtUnk23;
	kobjref<CKOBB> ckhdtUnk24;
	kobjref<CKOBB> ckhdtUnk25;
	kobjref<CKOBB> ckhdtUnk26;
	kobjref<CKOBB> ckhdtUnk27;
	kobjref<CKOBB> ckhdtUnk28;
	kobjref<CKOBB> ckhdtUnk29;
	kobjref<CKOBB> ckhdtUnk30;
	kobjref<CKBoundingSphere> ckhdtUnk31;
	float ckhdtUnk32;
	float ckhdtUnk33;
	float ckhdtUnk34;
	float ckhdtUnk35;
	float ckhdtUnk36;
	float ckhdtUnk37;
	float ckhdtUnk38;
	float ckhdtUnk39;
	float ckhdtUnk40;
	float ckhdtUnk41;
	float ckhdtUnk42;
	float ckhdtUnk43;
	float ckhdtUnk44;
	float ckhdtUnk45;
	float ckhdtUnk46;
	float ckhdtUnk47;
	float ckhdtUnk48;
	float ckhdtUnk49;
	float ckhdtUnk50;
	float ckhdtUnk51;
	float ckhdtUnk52;
	float ckhdtUnk53;
	float ckhdtUnk54;
	float ckhdtUnk55;
	float ckhdtUnk56;
	float ckhdtUnk57;
	float ckhdtUnk58;
	float ckhdtUnk59;
	float ckhdtUnk60;
	float ckhdtUnk61;
	float ckhdtUnk62;
	float ckhdtUnk63;
	float ckhdtUnk64;
	float ckhdtUnk65;
	float ckhdtUnk66;
	float ckhdtUnk67;
	float ckhdtUnk68;
	float ckhdtUnk69;
	float ckhdtUnk70;
	float ckhdtUnk71;
	float ckhdtUnk72;
	float ckhdtUnk73;
	float ckhdtUnk74;
	float ckhdtUnk75;
	float ckhdtUnk76;
	float ckhdtUnk77;
	float ckhdtUnk78;
	float ckhdtUnk79;
	float ckhdtUnk80;
	float ckhdtUnk81;
	float ckhdtUnk82;
	float ckhdtUnk83;
	float ckhdtUnk84;
	float ckhdtUnk85;
	float ckhdtUnk86;
	float ckhdtUnk87;
	float ckhdtUnk88;
	float ckhdtUnk89;
	float ckhdtUnk90;
	float ckhdtUnk91;
	float ckhdtUnk92;
	float ckhdtUnk93;
	float ckhdtUnk94;
	float ckhdtUnk95;
	float ckhdtUnk96;
	float ckhdtUnk97;
	float ckhdtUnk98;
	float ckhdtUnk99;
	float ckhdtUnk100;
	float ckhdtUnk101;
	float ckhdtUnk102;
	float ckhdtUnk103;
	float ckhdtUnk104;
	float ckhdtUnk105;
	float ckhdtUnk106;
	float ckhdtUnk107;
	float ckhdtUnk108;
	float ckhdtUnk109;
	float ckhdtUnk110;
	float ckhdtUnk111;
	float ckhdtUnk112;
	float ckhdtUnk113;
	float ckhdtUnk114;
	float ckhdtUnk115;
	float ckhdtUnk116;
	float ckhdtUnk117;
	float ckhdtUnk118;
	float ckhdtUnk119;
	float ckhdtUnk120;
	float ckhdtUnk121;
	kobjref<CAnimatedClone> ckhdtUnk122;
	kobjref<CAnimatedClone> ckhdtUnk123;
	kobjref<CAnimatedClone> ckhdtUnk124;
	kobjref<CAnimatedClone> ckhdtUnk125;
	kobjref<CAnimatedClone> ckhdtUnk126;
	kobjref<CAnimatedClone> ckhdtUnk127;
	kobjref<CAnimatedClone> ckhdtUnk128;
	kobjref<CAnimatedClone> ckhdtUnk129;
	kobjref<CAnimatedClone> ckhdtUnk130;
	kobjref<CAnimatedClone> ckhdtUnk131;
	kobjref<CAnimatedClone> ckhdtUnk132;
	kobjref<CAnimatedClone> ckhdtUnk133;
	kobjref<CAnimationDictionary> ckhdtUnk134;
	void reflectMembers2(MemberListener& r, KEnvironment* kenv);
};

struct CKHkTriangularTurtle : CKMRSubclass<CKHkTriangularTurtle, CKHkTurtle, 90> {
	kobjref<CKOBB> ckhttUnk0;
	kobjref<CKOBB> ckhttUnk1;
	kobjref<CKOBB> ckhttUnk2;
	kobjref<CKOBB> ckhttUnk3;
	kobjref<CKOBB> ckhttUnk4;
	kobjref<CKOBB> ckhttUnk5;
	kobjref<CKOBB> ckhttUnk6;
	kobjref<CKOBB> ckhttUnk7;
	kobjref<CKOBB> ckhttUnk8;
	kobjref<CKOBB> ckhttUnk9;
	kobjref<CKOBB> ckhttUnk10;
	kobjref<CKOBB> ckhttUnk11;
	kobjref<CKOBB> ckhttUnk12;
	kobjref<CKOBB> ckhttUnk13;
	kobjref<CKOBB> ckhttUnk14;
	kobjref<CKBoundingSphere> ckhttUnk15;
	float ckhttUnk16;
	float ckhttUnk17;
	float ckhttUnk18;
	float ckhttUnk19;
	float ckhttUnk20;
	float ckhttUnk21;
	float ckhttUnk22;
	float ckhttUnk23;
	float ckhttUnk24;
	float ckhttUnk25;
	float ckhttUnk26;
	float ckhttUnk27;
	float ckhttUnk28;
	float ckhttUnk29;
	float ckhttUnk30;
	float ckhttUnk31;
	float ckhttUnk32;
	float ckhttUnk33;
	float ckhttUnk34;
	float ckhttUnk35;
	float ckhttUnk36;
	float ckhttUnk37;
	float ckhttUnk38;
	float ckhttUnk39;
	float ckhttUnk40;
	float ckhttUnk41;
	float ckhttUnk42;
	float ckhttUnk43;
	float ckhttUnk44;
	float ckhttUnk45;
	float ckhttUnk46;
	float ckhttUnk47;
	float ckhttUnk48;
	float ckhttUnk49;
	float ckhttUnk50;
	float ckhttUnk51;
	float ckhttUnk52;
	float ckhttUnk53;
	float ckhttUnk54;
	float ckhttUnk55;
	float ckhttUnk56;
	float ckhttUnk57;
	kobjref<CAnimatedClone> ckhttUnk58;
	kobjref<CAnimatedClone> ckhttUnk59;
	kobjref<CAnimatedClone> ckhttUnk60;
	kobjref<CAnimatedClone> ckhttUnk61;
	void reflectMembers2(MemberListener& r, KEnvironment* kenv);
};

struct CKHkBoss : CKMRSubclass<CKHkBoss, CKHook, 177> {
	std::array<float, 3> ckhbUnk3;
	float ckhbUnk4;
	std::array<float, 38> ckhbUnk5;
	std::array<float, 3> ckhbUnk6;
	std::array<int32_t, 3> ckhbUnk7;
	uint8_t ckhbUnk8;
	uint8_t ckhbUnk9;
	std::array<float, 19> ckhbUnk10;
	uint8_t ckhbUnk11;
	std::array<float, 19> ckhbUnk12;
	uint8_t ckhbUnk13;
	std::array<float, 19> ckhbUnk14;
	uint8_t ckhbUnk15;
	std::array<float, 19> ckhbUnk16;
	uint8_t ckhbUnk17;
	std::array<float, 19> ckhbUnk18;
	uint8_t ckhbUnk19;
	float ckhbUnk20;
	float ckhbUnk21;
	int32_t ckhbUnk22;
	float ckhbUnk23;
	float ckhbUnk24;
	float ckhbUnk25;
	float ckhbUnk26;
	int32_t ckhbUnk27;
	float ckhbUnk28;
	float ckhbUnk29;
	float ckhbUnk30;
	float ckhbUnk31;
	int32_t ckhbUnk32;
	float ckhbUnk33;
	float ckhbUnk34;
	kobjref<CKSoundDictionaryID> ckhbUnk35;
	std::array<KPostponedRef<CKObject>, 4> ckhbUnk36;
	kobjref<CKProjectileTypeBase> ckhbUnk37;
	int32_t ckhbUnk38;
	std::array<float, 3> ckhbUnk39;
	kobjref<CKProjectileTypeBase> ckhbUnk40;
	int32_t ckhbUnk41;
	std::array<float, 3> ckhbUnk42;
	kobjref<CKProjectileTypeBase> ckhbUnk43;
	int32_t ckhbUnk44;
	std::array<float, 3> ckhbUnk45;
	kobjref<CKProjectileTypeBase> ckhbUnk46;
	int32_t ckhbUnk47;
	std::array<float, 3> ckhbUnk48;
	std::array<kobjref<CKObject>, 7> ckhbUnk49;
	kobjref<CNode> ckhbUnk50;
	kobjref<CNode> ckhbUnk51;
	kobjref<CKFlaggedPath> ckhbUnk52;
	std::array<kobjref<CKObject>, 3> ckhbUnk53;
	kobjref<CClone> ckhbUnk54;
	kobjref<CKAABB> ckhbUnk55;
	kobjref<CKAABB> ckhbUnk56;
	kobjref<CKShadowCpnt> ckhbUnk57;
	kobjref<CClone> ckhbUnk58;
	kobjref<CKAABB> ckhbUnk59;
	kobjref<CKAABB> ckhbUnk60;
	kobjref<CKShadowCpnt> ckhbUnk61;
	kobjref<CClone> ckhbUnk62;
	kobjref<CKAABB> ckhbUnk63;
	kobjref<CKAABB> ckhbUnk64;
	kobjref<CKShadowCpnt> ckhbUnk65;
	kobjref<CClone> ckhbUnk66;
	kobjref<CKAABB> ckhbUnk67;
	kobjref<CKAABB> ckhbUnk68;
	kobjref<CKShadowCpnt> ckhbUnk69;
	struct BossSomething {
		kobjref<CClone> ckhbUnk70;
		kobjref<CClone> ckhbUnk71;
		kobjref<CDynamicGround> ckhbUnk72;
		kobjref<CKAABB> ckhbUnk73;
		kobjref<CKAABB> ckhbUnk74;
	};
	std::array<BossSomething, 8> ckhbSomethings;
	EventNode ckhbUnk110;
	EventNode ckhbUnk111;
	EventNode ckhbUnk112;
	EventNode ckhbUnk113;
	EventNode ckhbUnk114;
	EventNode ckhbUnk115;
	float ckhbUnk116;
	float ckhbUnk117;
	std::array<float, 2> ckhbUnk118;
	std::string ckhbUnk119;
	int32_t ckhbUnk120;
	float ckhbUnk121;
	float ckhbUnk122;
	float ckhbUnk123;
	float ckhbUnk124;
	float ckhbUnk125;
	float ckhbUnk126;
	float ckhbUnk127;
	kobjref<CKSoundDictionaryID> ckhbUnk128;
	kobjref<CKSpline4L> ckhbUnk129;
	void reflectMembers2(MemberListener& r, KEnvironment* kenv);
};

struct CKHkTrioCatapult : CKMRSubclass<CKHkTrioCatapult, CKHook, 190> {
	uint8_t ckhtcUnk0;
	kobjref<CAnimatedNode> ckhtcUnk1;
	KPostponedRef<CGround> ckhtcUnk2;
	kobjref<CSGBranch> ckhtcUnk3;
	kobjref<CSGBranch> ckhtcUnk4;
	kobjref<CSGBranch> ckhtcUnk5;
	kobjref<CKFlaggedPath> ckhtcUnk6;
	float ckhtcUnk7;
	float ckhtcUnk8;
	float ckhtcUnk9;
	float ckhtcUnk10;
	EventNode ckhtcUnk11;
	EventNode ckhtcUnk12;
	EventNode ckhtcUnk13;
	EventNode ckhtcUnk14;
	kobjref<CAnimationDictionary> ckhtcUnk15;
	kobjref<CKSoundDictionaryID> ckhtcUnk16;
	uint8_t ckhtcSector;
	void reflectMembers2(MemberListener& r, KEnvironment* kenv);
};

struct CKHkObelixCatapult : CKMRSubclass<CKHkObelixCatapult, CKHook, 191> {
	float ckhocUnk0;
	Vector3 ckhocUnk1;
	KPostponedRef<CAnimatedNode> ckhocUnk2;
	KPostponedRef<CDynamicGround> ckhocUnk3;
	KPostponedRef<CSGBranch> ckhocUnk4;
	kobjref<CAnimationDictionary> ckhocUnk5;
	kobjref<CKSoundDictionaryID> ckhocUnk6;
	void reflectMembers2(MemberListener& r, KEnvironment* kenv);
};

struct CKHkRomanArcher : CKMRSubclass<CKHkRomanArcher, CKHkSquadSeizableEnemy, 95> {
	kobjref<CClone> ckhraUnk0;
	kobjref<CAnimatedClone> ckhraUnk1;
	kobjref<CAnimatedClone> ckhraUnk2;
	uint8_t ckhraUnk3;
	std::array<float, 7> ckhraUnk4;
	kobjref<CAnimatedClone> ckhraUnk5;
	uint8_t ckhraUnk6;
	std::array<float, 7> ckhraUnk7;
	kobjref<CParticlesNodeFx> ckhraUnk8;
	kobjref<CParticlesNodeFx> ckhraUnk9;
	kobjref<CParticlesNodeFx> ckhraUnk10;
	kobjref<CParticlesNodeFx> ckhraUnk11;
	kobjref<CAnimationDictionary> ckhraUnk12;
	kobjref<CAnimationDictionary> ckhraUnk13;
	uint8_t ckhraUnk14;
	uint8_t ckhraUnk15;
	kobjref<CKProjectileTypeBallisticPFX> ckhraUnk16;
	kobjref<CKSoundDictionaryID> ckhraUnk17;
	void reflectMembers2(MemberListener& r, KEnvironment* kenv);
};

struct CKHkBasicEnemyLeader : CKMRSubclass<CKHkBasicEnemyLeader, CKHkBasicEnemy, 148> {
	kobjref<CAnimationDictionary> ckhbelUnk0;
	kobjref<CKSoundDictionaryID> ckhbelUnk1;
	void reflectMembers2(MemberListener& r, KEnvironment* kenv);
};

// Unknown hook classes. To implement later!
struct CKHkWaterJet : CKPartlyUnknown<CKHook, 76> {};
struct CKHkInterfaceShop : CKPartlyUnknown<CKHook, 144> {};
struct CKHkInterfaceDemo : CKPartlyUnknown<CKHook, 179> {};

///--- Hook life classes ---///

struct CKHkAsterixLife : CKSubclass<CKHookLife, 27> {};

struct CKHkBoatLife : CKSubclass<CKHookLife, 55> {
	kobjref<CKHook> boatHook;

	void deserialize(KEnvironment* kenv, File *file, size_t length) override;
	void serialize(KEnvironment* kenv, File *file) override;
};

struct CKHkObelixLife : CKSubclass<CKHookLife, 57> {};
struct CKHkMecaLife : CKSubclass<CKHookLife, 59> {};
struct CKHkIdefixLife : CKSubclass<CKHookLife, 66> {};
struct CKHkEnemyLife : CKSubclass<CKHookLife, 93> {};
struct CKHkTriangularTurtleLife : CKSubclass<CKHookLife, 95> {};

struct CKHkAnimatedCharacterLife : CKSubclass<CKHookLife, 99> {};
struct CKHkSquareTurtleLife : CKSubclass<CKHookLife, 102> {};
struct CKHkDonutTurtleLife : CKSubclass<CKHookLife, 104> {};
struct CKHkPyramidalTurtleLife : CKSubclass<CKHookLife, 105> {};
struct CKHkCatapultLife : CKSubclass<CKHookLife, 108> {};

struct CKHkSkyLife : CKSubclass<CKHookLife, 112> {
	uint32_t skyColor, cloudColor;

	void deserialize(KEnvironment* kenv, File *file, size_t length) override;
	void serialize(KEnvironment* kenv, File *file) override;
};

struct CKHkWaterLife : CKSubclass<CKHookLife, 115> {};
struct CKHkBossLife : CKSubclass<CKHookLife, 118> {};
struct CKHkWaterFxLife : CKSubclass<CKHookLife, 120> {};
struct CKHkAsterixCheckpointLife : CKSubclass<CKHookLife, 124> {};
struct CKHkWaterFallLife : CKSubclass<CKHookLife, 125> {};
